#!groovy

/**
 * Jenkinsfile for Titanium
 *
 * v1.0.2
 *
 * Pipeline script for running in Jenkins - Multibranch Pipeline projects.
 * Steps this pipeline covers:
 * 1. Setup: checkout repo, determine if it's PR or Environment branch, othwerwise skip build
 * 2. Build: build the project for simulator (PR), adhoc (any other environment), app/play store (production, if required)
 * 3. Deploy and Notify: upload build(s) in Apperian and send message in Slack about the build * 
 */

library 'anexinet@master' _;

isPR = env.BRANCH_NAME.startsWith('PR-');
def isValidBranch = false;
def configuration = [
    buildAgent: 'Titanium && Xcode11',
    buildSignFolder: 'sign/',
    
    iosP12File: 'ios-certificate.p12',
    iosP12PasswordId: 'p12-dll-enterprise-password-text',
    iosCertificate: 'dE LAGE LANDEN FINANCIAL SERVICES, INC.',
    iosProvisioningProfile: 'f0d1f4eb-8ee1-485e-b873-69e2329a0eb0',

    appcCredentialsId: 'appcelerator-dll-pabloguevara-userpass',
    appcOrgId: 'appcelerator-dll-orgid-text',
    
    apperianCredentialsId: 'apperian-dll-pabloguevara-userpass',
    
    slackChannel: '#dll',
    slackUrlIos: '',
    slackUrlAndroid: 'N/A',
    slackIncludeChangeset: true
];

// You can specify settings per branch in a switch statement:

switch(env.BRANCH_NAME) {
    case 'test':
        isValidBranch = true;
        configuration.slackUrlIos = 'https://is.gd/o9c8kE';
        configuration.iosProvisioningProfile = 'cf3ab825-dd39-4cd9-b689-3bac7a37c737';
        break;

    case 'acc':
        isValidBranch = true;
        configuration.slackUrlIos = 'https://is.gd/z0tXiz';
        configuration.iosProvisioningProfile = 'eb9063c9-ca63-40a5-8346-876a8bc554c4';
        break;

    case 'stage':
        isValidBranch = true;
        configuration.slackUrlIos = 'https://is.gd/9XgLwp';
        configuration.iosProvisioningProfile = '7c40edc3-4afa-469c-b135-8cc6cc4da8cf';
        break;

    case 'demo':
        isValidBranch = true;
        configuration.slackUrlIos = 'https://is.gd/9jUC9I';
        configuration.iosProvisioningProfile = '95ce9a05-340c-4439-9739-a49489ed1725';
        break;

    case 'sit_tst':
        isValidBranch = true;
        configuration.slackUrlIos = 'https://is.gd/BkJ6VG';
        configuration.iosProvisioningProfile = '07a0ae4d-edae-435a-b6ad-258c6f5f1f73';
        break;

    case 'sit_acc':
        isValidBranch = true;
        configuration.slackUrlIos = 'https://is.gd/KbTi5K';
        configuration.iosProvisioningProfile = 'e38459da-9fbb-45aa-ab62-c518eb35495c';
        break;
}

isValidBranch = isValidBranch || isPR;

if (!isValidBranch) {
    echo "**Branch ${env.BRANCH_NAME} not supported for builds, review this project configuration in Jenkins**";
    currentBuild.result = 'FAILURE';
    return;
} 

def buildAgent = configuration.buildAgent;

node(buildAgent) {    
    try {
        checkout scm;

        def buildInfo = build(configuration);

        if (isPR) {
            return;
        }

        deploy(buildInfo, configuration);
        notify(buildInfo, configuration);
    } catch (err) {
        currentBuild.result = 'FAILURE';
        print err.toString();
    } finally {
        deleteDir();
    }
}

/**
 * @function
 * Performs the build process for iOS in Titanium
 * @param <dict> configuration [
 *      appcCredentialsId: <string>, 
 *      appcOrgId: <string>
 *  ]
 * @return <dict> [
 *      appId: <string>, 
 *      appName: <string>, 
 *      appVersion: <string>, 
 *      buildPaths: [ios: <string>, android: <string>]
 *  ]
 *
 */
def build(configuration) {
    def appcCredentialsId = configuration.appcCredentialsId;
    def appcOrgId = configuration.appcOrgId;

    def buildInfo = [:];

    stage('Build') {
        buildInfo = titanium.getAppInfo();

        lock('appc_session') {
            withCredentials([
                    usernamePassword(
                        credentialsId: appcCredentialsId, 
                        usernameVariable: 'APPC_USERNAME',
                        passwordVariable: 'APPC_PASSWORD'), 
                    string(
                        credentialsId: appcOrgId, 
                        variable: 'APPC_ORG_ID')
                ]) 
            {
                
                titanium.checkSDK([
                    appcUsername: APPC_USERNAME,
                    appcPassword: APPC_PASSWORD,
                    appcOrgId: APPC_ORG_ID
                ]);
                
                titanium.clean();

                if (isPR) {
                    titanium.compileTitanium([
                        platform: 'ios',
                        type: 'simulator'
                    ]);

                    return;
                }
                
                titanium.appcLogin([
                    appcUsername: APPC_USERNAME,
                    appcPassword: APPC_PASSWORD,
                    appcOrgId: APPC_ORG_ID
                ]);

                buildInfo.buildPaths = [
                    ios: buildIOS(configuration)
                ];
            }
        }
    }

    return buildInfo;
}

/**
 * @function
 * Performs the build process for iOS in Titanium
 * @param <dict> conifguration [
 *      buildSignFolder: <string> Folder containing the P12 and Prov. Profiles
 *      iosP12File: <string> Name of the P12 file (relative to `buildSignFolder`)
 *      iosP12PasswordId: <string> PasswordId for the P12 file
 *      iosCertificate: <string> Certificate Name to use
 *      iosProvisioningProfile: <string> Prov. Profile UUID
 *  ]
 * @return <string> path of the IPA generated
 *
 */
def buildIOS(configuration) {
    def buildSignFolder = configuration.buildSignFolder;
    def iosP12File = configuration.iosP12File;
    def iosP12PasswordId = configuration.iosP12PasswordId;
    def iosCertificate = configuration.iosCertificate;
    def iosProvisioningProfile = configuration.iosProvisioningProfile;

    def result;
    try {
        if (!fileExists(buildSignFolder)) {
            echo "Signing folder $buildSignFolder does not exist. Aborting"

            throw new IOException();
        }
        
        dir(buildSignFolder) {
            withCredentials([
                string(
                    credentialsId: iosP12PasswordId, 
                    variable: 'P12_PASS')
            ]) {
                xcodeSign.loadTempKeychain([
                    p12File: iosP12File,
                    p12Password: P12_PASS
                ]);

                xcodeSign.loadProvisioningProfiles();
            }
        }

        def buildOptions = [
            platform: 'ios',
            type: 'adhoc',
            iosCertName: iosCertificate,
            iosPP: iosProvisioningProfile
        ];
        
        result = titanium.compileTitanium(buildOptions);
    } catch(Error err) {
        print err;
    } finally {
        xcodeSign.deleteTempKeychains()
        xcodeSign.deleteProvisioningProfiles()
    }

    return result;
}

/**
 * @function
 * Deploys the builds (IPA, APK) to internal app catalogs (Apperian in this case)
 * @param <dict> buildInfo [
 *      appId: <string>
 *      appName: <string>
 *      appVersion: <string>
 *      buildPaths: <dict> [
 *           ios: <string>
 *           android: <string>
 *      ]
 *  ]
 * @param <dict> configuration [
 *      apperianCredentialsId: <string>
 *  ]
 */
def deploy(buildInfo, configuration) {
    def apperianCredentialsId = configuration.apperianCredentialsId;
    def appId = buildInfo.appId;
    def appName = buildInfo.appName;
    def appVersion = buildInfo.appVersion;
    def buildPaths = buildInfo.buildPaths;

    stage('deploy') {
        withCredentials([
            usernamePassword(
                credentialsId: apperianCredentialsId,
                usernameVariable: 'username',
                passwordVariable: 'password')
        ]) {
            def timeStamp = Calendar.getInstance().getTime().format('YYYYMMdd-hhmmss',TimeZone.getTimeZone('UTC'));
            def deploySteps = [:];

            uploads.toApperian([
                username: username,
                password: password,
                appId: appId,
                platform: 'ios',
                name: appName,
                author: 'Anexinet-CI',
                version: appVersion,
                path: buildPaths.ios,
                notes: "Build at $timeStamp (UTC)"
            ]);      
        }
    }
}

/**
 * @function
 * Sends a notification that the build completed, in this case, to Slack
 * @param <dict> buildInfo [
 *      appVersion: <string>
 *  ]
 * @param <dict> configuration [
 *      slackChannel: <string>
 *      slackUrlIos: <string>
 *      slackUrlAndroid: <string>
 *      slackIncludeChangeset: <boolean>
 *  ]
 */
def notify(buildInfo, configuration) {
    def slackChannel = configuration.slackChannel;
    def slackUrlIos = configuration.slackUrlIos;
    def slackUrlAndroid = configuration.slackUrlAndroid;
    def slackIncludeChangeset = configuration.slackIncludeChangeset;
    
    def appName = buildInfo.appName;
    def appVersion = buildInfo.appVersion;

    notifications.sendSlackMessage([
        channel: slackChannel,
        name: appName,
        version: appVersion,
        iosUrl: slackUrlIos,
        androidUrl: slackUrlAndroid,
        includeChangeset: slackIncludeChangeset
    ]);
}